output:
  text: Hello World

image: svr
company: yourcompany
version: latest

# Details of class inheriting from Wrapper
wrapper-info: svr.wrapper.PipelineWrapper

surround:
  path: '/Users/saikrishna/Documents/GitHub/Surround_AI_Suqad_2/svr/data/AAPL.csv'